# Generated by Django 5.0.3 on 2024-04-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0003_remove_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(editable=False, max_length=100, verbose_name='رمز عبور'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='repeat_password',
            field=models.CharField(editable=False, max_length=100, verbose_name='تکرار رمز عبور'),
        ),
    ]
