# Generated by Django 5.0.3 on 2024-04-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_module', '0001_initial'),
        ('user_module', '0005_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cart',
            field=models.ManyToManyField(blank=True, null=True, related_name='cart', to='book_module.book', verbose_name='سبد خرید'),
        ),
    ]
