# Generated by Django 5.0.3 on 2024-04-11 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام نویسنده')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات/بیوگرافی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='author', verbose_name='تصویر نویسنده')),
                ('rate', models.FloatField(default=5, verbose_name='امتیاز')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='تاریخ مرگ')),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسندگان',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته بندی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category', verbose_name='نمونه تصویر دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام ناشر')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('rate', models.FloatField(default=5, verbose_name='امتیاز')),
                ('books', models.IntegerField(default=3, verbose_name='تعداد کتاب های ناشر')),
                ('image', models.ImageField(blank=True, null=True, upload_to='publisher', verbose_name='تصویر ناشر')),
            ],
            options={
                'verbose_name': 'ناشر',
                'verbose_name_plural': 'ناشر ها',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام کتاب')),
                ('front_cover_image', models.ImageField(blank=True, null=True, upload_to='book', verbose_name='تصویر جلد جلوی کتاب')),
                ('back_cover_image', models.ImageField(blank=True, null=True, upload_to='book', verbose_name='تصویر جلد پشت کتاب')),
                ('translator', models.CharField(blank=True, max_length=100, null=True, verbose_name='مترجم')),
                ('language', models.CharField(max_length=100, verbose_name='زبان')),
                ('pages', models.IntegerField(verbose_name='تعداد صفحات')),
                ('weight', models.FloatField(help_text='به گرم', verbose_name='وزن')),
                ('price', models.IntegerField(help_text='به تومان', verbose_name='قیمت')),
                ('publish_date', models.DateField(help_text='تاریخ انتشار کتاب', verbose_name='تاریخ انتشار')),
                ('description', models.TextField(verbose_name='خلاصه کتاب')),
                ('stock', models.IntegerField(verbose_name='موجودی')),
                ('sales', models.IntegerField(default=0, verbose_name='تعداد فروش')),
                ('isbn', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ISBN')),
                ('rate', models.FloatField(default=5, verbose_name='امتیاز')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, null=True, verbose_name='url title')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_module.author', verbose_name='نویسنده')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_module.category', verbose_name='دسته بندی')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_module.publisher', verbose_name='ناشر')),
            ],
            options={
                'verbose_name': 'کتاب',
                'verbose_name_plural': 'کتاب ها',
            },
        ),
    ]
