# Generated by Django 5.0.3 on 2024-04-11 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('comment', models.TextField(verbose_name='نظر')),
                ('sold_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_module.book', verbose_name='کتاب خریداری شده')),
            ],
        ),
    ]
